// <auto-generated />
using System;
using BookIllustration_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookIllustration_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823142915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterIllustrationPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChapterId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterIllustrationPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.PipelineStep", b =>
                {
                    b.Property<Guid>("PipelineStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepData")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepName")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PipelineStepId");

                    b.HasIndex("ProjectId", "StepName")
                        .IsUnique();

                    b.ToTable("PipelineSteps");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookTextPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserEmail");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChapterCharacters", b =>
                {
                    b.Property<int>("ChaptersChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharactersCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChaptersChapterId", "CharactersCharacterId");

                    b.HasIndex("CharactersCharacterId");

                    b.ToTable("ChapterCharacters");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.Chapter", b =>
                {
                    b.HasOne("BookIllustration_Backend.Models.Entities.Project", "Project")
                        .WithMany("Chapters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.Character", b =>
                {
                    b.HasOne("BookIllustration_Backend.Models.Entities.Project", "Project")
                        .WithMany("Characters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.PipelineStep", b =>
                {
                    b.HasOne("BookIllustration_Backend.Models.Entities.Project", "Project")
                        .WithMany("PipelineSteps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.Project", b =>
                {
                    b.HasOne("BookIllustration_Backend.Models.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChapterCharacters", b =>
                {
                    b.HasOne("BookIllustration_Backend.Models.Entities.Chapter", null)
                        .WithMany()
                        .HasForeignKey("ChaptersChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookIllustration_Backend.Models.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.Project", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Characters");

                    b.Navigation("PipelineSteps");
                });

            modelBuilder.Entity("BookIllustration_Backend.Models.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
